//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winwise.SPMailing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Winwise_SPMailing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Winwise_SPMailing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Winwise.SPMailing.Resources.Winwise.SPMailing", typeof(Winwise_SPMailing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ContentType_Category_Name {
            get {
                return ResourceManager.GetString("ContentType_Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category template.
        /// </summary>
        internal static string ContentType_CategoryTemplate_Name {
            get {
                return ResourceManager.GetString("ContentType_CategoryTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact recipient.
        /// </summary>
        internal static string ContentType_ContactRecipient_Name {
            get {
                return ResourceManager.GetString("ContentType_ContactRecipient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing.
        /// </summary>
        internal static string ContentType_Mailing_Name {
            get {
                return ResourceManager.GetString("ContentType_Mailing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing definition.
        /// </summary>
        internal static string ContentType_MailingDefinition_Name {
            get {
                return ResourceManager.GetString("ContentType_MailingDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing template.
        /// </summary>
        internal static string ContentType_MailingTemplate_Name {
            get {
                return ResourceManager.GetString("ContentType_MailingTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients list.
        /// </summary>
        internal static string ContentType_RecipientsList_Name {
            get {
                return ResourceManager.GetString("ContentType_RecipientsList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find lookup field : property key {0} does not exist.
        /// </summary>
        internal static string Error_Lookup_PropertyKeyNotFound {
            get {
                return ResourceManager.GetString("Error_Lookup_PropertyKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract SharePoint content to generate and send mailings such as newsletters.
        /// </summary>
        internal static string Feature_Web_Mailings_Description {
            get {
                return ResourceManager.GetString("Feature_Web_Mailings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winwise - SPMailing.
        /// </summary>
        internal static string Feature_Web_Mailings_Title {
            get {
                return ResourceManager.GetString("Feature_Web_Mailings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the mailing definition workflow will automatically generate a mailing every X days, X corresponding to the &quot;DaysOffset filter&quot; field. Use SharePoint alerts on the mailings list to be notified. Mailings won&apos;t be sent automatically.
        ///If enabled, the first mailing will be generated as soon as this item is modified..
        /// </summary>
        internal static string Field_AutoGenerate_Description {
            get {
                return ResourceManager.GetString("Field_AutoGenerate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic generation.
        /// </summary>
        internal static string Field_AutoGenerate_Title {
            get {
                return ResourceManager.GetString("Field_AutoGenerate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories that will be rendered in the mailing.
        /// </summary>
        internal static string Field_Categories_Description {
            get {
                return ResourceManager.GetString("Field_Categories_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Field_Categories_Title {
            get {
                return ResourceManager.GetString("Field_Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT transformation used to render this category.
        /// </summary>
        internal static string Field_CategoryTemplate_Description {
            get {
                return ResourceManager.GetString("Field_CategoryTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Template.
        /// </summary>
        internal static string Field_CategoryTemplate_Title {
            get {
                return ResourceManager.GetString("Field_CategoryTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_ContactRecipients_Description {
            get {
                return ResourceManager.GetString("Field_ContactRecipients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Recipients.
        /// </summary>
        internal static string Field_ContactRecipients_Title {
            get {
                return ResourceManager.GetString("Field_ContactRecipients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a mailing is generated, categories that use date filters in their query can use this field to filter items that have been modified or created within the X previous days.
        /// </summary>
        internal static string Field_DaysOffset_Description {
            get {
                return ResourceManager.GetString("Field_DaysOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaysOffset filter.
        /// </summary>
        internal static string Field_DaysOffset_Title {
            get {
                return ResourceManager.GetString("Field_DaysOffset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_Footer_Description {
            get {
                return ResourceManager.GetString("Field_Footer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string Field_Footer_Title {
            get {
                return ResourceManager.GetString("Field_Footer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_From_Adress_Description {
            get {
                return ResourceManager.GetString("Field_From_Adress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (adress).
        /// </summary>
        internal static string Field_From_Adress_Title {
            get {
                return ResourceManager.GetString("Field_From_Adress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_From_DisplayName_Description {
            get {
                return ResourceManager.GetString("Field_From_DisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (display name).
        /// </summary>
        internal static string Field_From_DisplayName_Title {
            get {
                return ResourceManager.GetString("Field_From_DisplayName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this field to specify which user account is used to execute content extraction during the mailing generation. Warning : if this field is not set, system account will be used..
        /// </summary>
        internal static string Field_GenerationUser_Description {
            get {
                return ResourceManager.GetString("Field_GenerationUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonate User.
        /// </summary>
        internal static string Field_GenerationUser_Title {
            get {
                return ResourceManager.GetString("Field_GenerationUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_Header_Description {
            get {
                return ResourceManager.GetString("Field_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string Field_Header_Title {
            get {
                return ResourceManager.GetString("Field_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the display name of the category.It can be used in the category&apos;s XSL template.
        /// </summary>
        internal static string Field_Label_Description {
            get {
                return ResourceManager.GetString("Field_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Field_Label_Title {
            get {
                return ResourceManager.GetString("Field_Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_Log_Description {
            get {
                return ResourceManager.GetString("Field_Log_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Field_Log_Title {
            get {
                return ResourceManager.GetString("Field_Log_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_MailBody_Description {
            get {
                return ResourceManager.GetString("Field_MailBody_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Body.
        /// </summary>
        internal static string Field_MailBody_Title {
            get {
                return ResourceManager.GetString("Field_MailBody_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing definition from which this mailing has been generated.
        /// </summary>
        internal static string Field_MailingDefinition_Description {
            get {
                return ResourceManager.GetString("Field_MailingDefinition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Definition.
        /// </summary>
        internal static string Field_MailingDefinition_Title {
            get {
                return ResourceManager.GetString("Field_MailingDefinition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML template that will be used to render the mailing.
        /// </summary>
        internal static string Field_MailingTemplate_Description {
            get {
                return ResourceManager.GetString("Field_MailingTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Template.
        /// </summary>
        internal static string Field_MailingTemplate_Title {
            get {
                return ResourceManager.GetString("Field_MailingTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_MailSubject_Description {
            get {
                return ResourceManager.GetString("Field_MailSubject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Subject.
        /// </summary>
        internal static string Field_MailSubject_Title {
            get {
                return ResourceManager.GetString("Field_MailSubject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint users and groups targeted by this recipients list.
        /// </summary>
        internal static string Field_PeopleAndGroupsRecipients_Description {
            get {
                return ResourceManager.GetString("Field_PeopleAndGroupsRecipients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Users.
        /// </summary>
        internal static string Field_PeopleAndGroupsRecipients_Title {
            get {
                return ResourceManager.GetString("Field_PeopleAndGroupsRecipients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAML Query that will filter items for this category.
        ///Example : &lt;Where&gt;&lt;Geq&gt;&lt;FieldRef Name=&quot;Modified&quot;/&gt;&lt;Value Type=&quot;DateTime&quot;&gt;&lt;Today OffsetDays=&quot;-[DAYSOFFSET]&quot;/&gt;&lt;/Value&gt;&lt;/Geq&gt;&lt;/Where&gt;&lt;OrderBy&gt;&lt;FieldRef Name=&quot;Modified&quot; Ascending=&apos;FALSE&apos; /&gt;&lt;/OrderBy&gt;.
        /// </summary>
        internal static string Field_Query_Description {
            get {
                return ResourceManager.GetString("Field_Query_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAML Query.
        /// </summary>
        internal static string Field_Query_Title {
            get {
                return ResourceManager.GetString("Field_Query_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_Recipients_Description {
            get {
                return ResourceManager.GetString("Field_Recipients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        internal static string Field_Recipients_Title {
            get {
                return ResourceManager.GetString("Field_Recipients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_RecipientsLists_Description {
            get {
                return ResourceManager.GetString("Field_RecipientsLists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients Lists.
        /// </summary>
        internal static string Field_RecipientsLists_Title {
            get {
                return ResourceManager.GetString("Field_RecipientsLists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_ReplyTo_Adress_Description {
            get {
                return ResourceManager.GetString("Field_ReplyTo_Adress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplyTo (adress).
        /// </summary>
        internal static string Field_ReplyTo_Adress_Title {
            get {
                return ResourceManager.GetString("Field_ReplyTo_Adress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Field_ReplyTo_DisplayName_Description {
            get {
                return ResourceManager.GetString("Field_ReplyTo_DisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplyTo (display name).
        /// </summary>
        internal static string Field_ReplyTo_DisplayName_Title {
            get {
                return ResourceManager.GetString("Field_ReplyTo_DisplayName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this mailing has been sent. A mailing cannot be sent twice..
        /// </summary>
        internal static string Field_Sent_Description {
            get {
                return ResourceManager.GetString("Field_Sent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Field_Sent_Title {
            get {
                return ResourceManager.GetString("Field_Sent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this category targets a site and all of it&apos;s sub sites, or only a single list.
        /// </summary>
        internal static string Field_Type_Description {
            get {
                return ResourceManager.GetString("Field_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Field_Type_Title {
            get {
                return ResourceManager.GetString("Field_Type_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url of the list or site (depending on the Type field) targeted by the query.
        /// </summary>
        internal static string Field_Url_Description {
            get {
                return ResourceManager.GetString("Field_Url_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Field_Url_Title {
            get {
                return ResourceManager.GetString("Field_Url_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates which fields must be retrieved by the category&apos;s query.
        /// </summary>
        internal static string Field_ViewFields_Description {
            get {
                return ResourceManager.GetString("Field_ViewFields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewFields.
        /// </summary>
        internal static string Field_ViewFields_Title {
            get {
                return ResourceManager.GetString("Field_ViewFields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string GenerateMailing_Processing_LeadingHTML {
            get {
                return ResourceManager.GetString("GenerateMailing_Processing_LeadingHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing generation in progress.
        /// </summary>
        internal static string GenerateMailing_Processing_TrailingHTML {
            get {
                return ResourceManager.GetString("GenerateMailing_Processing_TrailingHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in this list represent SharePoint content extractions that can be included in mailings.
        /// </summary>
        internal static string ListInstance_Categories_Description {
            get {
                return ResourceManager.GetString("ListInstance_Categories_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string ListInstance_Categories_Title {
            get {
                return ResourceManager.GetString("ListInstance_Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library contains XSL templates used to render categories.
        /// </summary>
        internal static string ListInstance_CategoryTemplates_Description {
            get {
                return ResourceManager.GetString("ListInstance_CategoryTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Templates.
        /// </summary>
        internal static string ListInstance_CategoryTemplates_Title {
            get {
                return ResourceManager.GetString("ListInstance_CategoryTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contact list&apos;s items can be used as recipients in recipients lists.
        /// </summary>
        internal static string ListInstance_ContactRecipients_Description {
            get {
                return ResourceManager.GetString("ListInstance_ContactRecipients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Recipients.
        /// </summary>
        internal static string ListInstance_ContactRecipients_Title {
            get {
                return ResourceManager.GetString("ListInstance_ContactRecipients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in this list represent pre-configured mailings. A workflow can be used to automatically generate them every X days, or they can be generated manually.
        /// </summary>
        internal static string ListInstance_MailingDefinitions_Description {
            get {
                return ResourceManager.GetString("ListInstance_MailingDefinitions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Definitions.
        /// </summary>
        internal static string ListInstance_MailingDefinitions_Title {
            get {
                return ResourceManager.GetString("ListInstance_MailingDefinitions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in this list are mailings that have been generated from mailing definitions, they can be sent from here. This list can also be used to hand-write mailings and send them..
        /// </summary>
        internal static string ListInstance_Mailings_Description {
            get {
                return ResourceManager.GetString("ListInstance_Mailings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailings.
        /// </summary>
        internal static string ListInstance_Mailings_Title {
            get {
                return ResourceManager.GetString("ListInstance_Mailings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library contain html templates used to generate mailings.
        /// </summary>
        internal static string ListInstance_MailingTemplates_Description {
            get {
                return ResourceManager.GetString("ListInstance_MailingTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Templates.
        /// </summary>
        internal static string ListInstance_MailingTemplates_Title {
            get {
                return ResourceManager.GetString("ListInstance_MailingTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list contains reusable lists of recipients used by mailing definitions.
        /// </summary>
        internal static string ListInstance_RecipientsLists_Description {
            get {
                return ResourceManager.GetString("ListInstance_RecipientsLists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients Lists.
        /// </summary>
        internal static string ListInstance_RecipientsLists_Title {
            get {
                return ResourceManager.GetString("ListInstance_RecipientsLists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing generation.
        /// </summary>
        internal static string Log_BeginGeneration {
            get {
                return ResourceManager.GetString("Log_BeginGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the mailing.
        /// </summary>
        internal static string Log_BeginSend {
            get {
                return ResourceManager.GetString("Log_BeginSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; : An error occured during generation.
        /// </summary>
        internal static string Log_Error_CategoryGenerationError {
            get {
                return ResourceManager.GetString("Log_Error_CategoryGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; : List {1} could not be found.
        /// </summary>
        internal static string Log_Error_ListNotFound {
            get {
                return ResourceManager.GetString("Log_Error_ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mailing has already been sent. It cannot be sent twice..
        /// </summary>
        internal static string Log_Error_MailingAlreadySent {
            get {
                return ResourceManager.GetString("Log_Error_MailingAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no mailing template associated to this mailing definition.
        /// </summary>
        internal static string Log_Error_NoMailingTemplate {
            get {
                return ResourceManager.GetString("Log_Error_NoMailingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; : An error occured during execution of the CAML query.
        /// </summary>
        internal static string Log_Error_QueryError {
            get {
                return ResourceManager.GetString("Log_Error_QueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An erreur occured while sending the mailing.
        /// </summary>
        internal static string Log_Error_SendError {
            get {
                return ResourceManager.GetString("Log_Error_SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; : query returned no results.
        /// </summary>
        internal static string Log_Info_EmptyCategory {
            get {
                return ResourceManager.GetString("Log_Info_EmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing sent to {0}.
        /// </summary>
        internal static string Log_Info_MailingSentTo {
            get {
                return ResourceManager.GetString("Log_Info_MailingSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact {0} (ID={1}) has no associated email.
        /// </summary>
        internal static string Log_Warning_ContactHasNoEmail {
            get {
                return ResourceManager.GetString("Log_Warning_ContactHasNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; : Field &quot;{1}&quot; could not be found or converted to a string.
        /// </summary>
        internal static string Log_Warning_ListFieldNotFound {
            get {
                return ResourceManager.GetString("Log_Warning_ListFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to send the mailing to {0}.
        /// </summary>
        internal static string Log_Warning_MailingCouldNotBeSentTo {
            get {
                return ResourceManager.GetString("Log_Warning_MailingCouldNotBeSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; : User {1} cannot access to .
        /// </summary>
        internal static string Log_Warning_UserCannotAccessListItem {
            get {
                return ResourceManager.GetString("Log_Warning_UserCannotAccessListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has no associated email.
        /// </summary>
        internal static string Log_Warning_UserHasNoEmail {
            get {
                return ResourceManager.GetString("Log_Warning_UserHasNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} could not be found.
        /// </summary>
        internal static string Log_Warning_UserNotFound {
            get {
                return ResourceManager.GetString("Log_Warning_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a new mailing from his mailing definition.
        /// </summary>
        internal static string Ribbon_GenerateMailing_ButtonGenerate_Description {
            get {
                return ResourceManager.GetString("Ribbon_GenerateMailing_ButtonGenerate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Ribbon_GenerateMailing_ButtonGenerate_Title {
            get {
                return ResourceManager.GetString("Ribbon_GenerateMailing_ButtonGenerate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ribbon_GenerateMailing_Group_Description {
            get {
                return ResourceManager.GetString("Ribbon_GenerateMailing_Group_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string Ribbon_GenerateMailing_Group_Title {
            get {
                return ResourceManager.GetString("Ribbon_GenerateMailing_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands related to SPMailing feature.
        /// </summary>
        internal static string Ribbon_GenerateMailing_Tab_Description {
            get {
                return ResourceManager.GetString("Ribbon_GenerateMailing_Tab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPMailing.
        /// </summary>
        internal static string Ribbon_GenerateMailing_Tab_Title {
            get {
                return ResourceManager.GetString("Ribbon_GenerateMailing_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the mailing to all recipients.
        /// </summary>
        internal static string Ribbon_Mailing_Button_Send_Description {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Button_Send_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Ribbon_Mailing_Button_Send_Title {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Button_Send_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the mailing to current user only.
        /// </summary>
        internal static string Ribbon_Mailing_Button_Test_Description {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Button_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Ribbon_Mailing_Button_Test_Title {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Button_Test_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ribbon_Mailing_Group_Description {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Group_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing.
        /// </summary>
        internal static string Ribbon_Mailing_Group_Title {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ribbon_Mailing_Tab_Description {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Tab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPMailing.
        /// </summary>
        internal static string Ribbon_Mailing_Tab_Title {
            get {
                return ResourceManager.GetString("Ribbon_Mailing_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string SendMailing_Processing_LeadingHTML {
            get {
                return ResourceManager.GetString("SendMailing_Processing_LeadingHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing is beeing sent.
        /// </summary>
        internal static string SendMailing_Processing_TrailingHTML {
            get {
                return ResourceManager.GetString("SendMailing_Processing_TrailingHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic generation is enabled but the days offset filter is not set or lesser than 1.
        /// </summary>
        internal static string Workflow_Error_DaysOffsetNotSet {
            get {
                return ResourceManager.GetString("Workflow_Error_DaysOffsetNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks workflow events.
        /// </summary>
        internal static string Workflow_HistoryList_Description {
            get {
                return ResourceManager.GetString("Workflow_HistoryList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow History.
        /// </summary>
        internal static string Workflow_HistoryList_Title {
            get {
                return ResourceManager.GetString("Workflow_HistoryList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating a new mailing.
        /// </summary>
        internal static string Workflow_Log_AutomaticGeneration {
            get {
                return ResourceManager.GetString("Workflow_Log_AutomaticGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mailing definition has been modified, terminating workflow.
        /// </summary>
        internal static string Workflow_Log_ItemChanged {
            get {
                return ResourceManager.GetString("Workflow_Log_ItemChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mailing definition is set to manual generation mode.
        /// </summary>
        internal static string Workflow_Log_ManualGeneration {
            get {
                return ResourceManager.GetString("Workflow_Log_ManualGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow terminating.
        /// </summary>
        internal static string Workflow_Log_Terminating {
            get {
                return ResourceManager.GetString("Workflow_Log_Terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for {0} until next generation.
        /// </summary>
        internal static string Workflow_Log_WaitForDaysOffset {
            get {
                return ResourceManager.GetString("Workflow_Log_WaitForDaysOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow started.
        /// </summary>
        internal static string Workflow_Log_WorkflowActivated {
            get {
                return ResourceManager.GetString("Workflow_Log_WorkflowActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential machine workflow that automatically generates mailings every X days if specified in the AutomaticGeneration field.
        /// </summary>
        internal static string Workflow_MailingDefinition_Description {
            get {
                return ResourceManager.GetString("Workflow_MailingDefinition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing generation.
        /// </summary>
        internal static string Workflow_MailingDefinition_Name {
            get {
                return ResourceManager.GetString("Workflow_MailingDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating.
        /// </summary>
        internal static string Workflow_Outcome_Generating {
            get {
                return ResourceManager.GetString("Workflow_Outcome_Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string Workflow_Outcome_Initializing {
            get {
                return ResourceManager.GetString("Workflow_Outcome_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Workflow_Outcome_Running {
            get {
                return ResourceManager.GetString("Workflow_Outcome_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating.
        /// </summary>
        internal static string Workflow_Outcome_Terminating {
            get {
                return ResourceManager.GetString("Workflow_Outcome_Terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string Workflow_Outcome_Waiting {
            get {
                return ResourceManager.GetString("Workflow_Outcome_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks workflow tasks.
        /// </summary>
        internal static string Workflow_TaskList_Description {
            get {
                return ResourceManager.GetString("Workflow_TaskList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Tasks.
        /// </summary>
        internal static string Workflow_TaskList_Title {
            get {
                return ResourceManager.GetString("Workflow_TaskList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles automatic generation if specified.
        /// </summary>
        internal static string WorkflowAssociation_MailingDefinition_Description {
            get {
                return ResourceManager.GetString("WorkflowAssociation_MailingDefinition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string WorkflowAssociation_MailingDefinition_Name {
            get {
                return ResourceManager.GetString("WorkflowAssociation_MailingDefinition_Name", resourceCulture);
            }
        }
    }
}
